#import <UIKit/UIKit.h>
#import "ActionGestureHelper.h"

%group ActionGestureOfficialSettings
%hook NSUserDefaults
- (void)setObject:(id)value forKey:(NSString *)key { %orig; [ActionGestureHelper.sharedHelper systemActionPreferenceDidChangeForKey:key]; }
- (void)removeObjectForKey:(NSString *)key { %orig; [ActionGestureHelper.sharedHelper systemActionPreferenceDidChangeForKey:key]; }
%end

%hook ActionButtonSettings
%new - (UIButton *)ag_selector:(NSString *)title menu:(UIMenu *)menu { UIButton *b=[UIButton buttonWithType:UIButtonTypeSystem]; b.titleLabel.font=[UIFont systemFontOfSize:12.5 weight:UIFontWeightMedium]; [b setTitle:title forState:UIControlStateNormal]; [b setTitleColor:UIColor.whiteColor forState:UIControlStateNormal]; UIImageSymbolConfiguration *cfg=[UIImageSymbolConfiguration configurationWithPointSize:6.5 weight:UIImageSymbolWeightMedium scale:UIImageSymbolScaleSmall]; UIImage *image=[[UIImage systemImageNamed:@"chevron.up.chevron.down"] imageWithConfiguration:cfg]; [b setImage:image forState:UIControlStateNormal]; b.tintColor=UIColor.whiteColor; b.imageEdgeInsets=UIEdgeInsetsMake(0,3,0,0); b.contentEdgeInsets=UIEdgeInsetsZero; b.menu=menu; b.showsMenuAsPrimaryAction=YES; [b sizeToFit]; return b; }
%new - (UIButton *)ag_helpButton { UIButton *b=[UIButton buttonWithType:UIButtonTypeSystem]; UIImageSymbolConfiguration *cfg=[UIImageSymbolConfiguration configurationWithPointSize:11 weight:UIImageSymbolWeightRegular scale:UIImageSymbolScaleSmall]; [b setImage:[[UIImage systemImageNamed:@"questionmark.circle"] imageWithConfiguration:cfg] forState:UIControlStateNormal]; b.tintColor=UIColor.whiteColor; b.contentEdgeInsets=UIEdgeInsetsMake(0,3,0,0); [b addTarget:self action:@selector(ag_showHelp) forControlEvents:UIControlEventTouchUpInside]; return b; }
%new - (void)ag_showHelp { UIAlertController *a=[UIAlertController alertControllerWithTitle:@"使用说明" message:@"单击、双击、长按可分别保存系统动作。\n\n系统动作优先：选择专注模式、相机、手电筒等系统动作时，快捷动作会自动关闭。\n\n只有选择“无操作”后，才可为该手势选择微信或支付宝快捷动作。" preferredStyle:UIAlertControllerStyleAlert]; [a addAction:[UIAlertAction actionWithTitle:@"知道了" style:UIAlertActionStyleDefault handler:nil]]; [self presentViewController:a animated:YES completion:nil]; }
%new - (void)ag_installSelectors { ActionGestureHelper *h=ActionGestureHelper.sharedHelper; UIButton *g=[self ag_selector:[h titleForGesture:h.currentGesture] menu:[self ag_gestureMenu]]; UIButton *s=[self ag_selector:[h titleForShortcut:[h shortcutForGesture:h.currentGesture]] menu:[self ag_shortcutMenu]]; UIButton *q=[self ag_helpButton]; self.navigationItem.rightBarButtonItems=@[[[UIBarButtonItem alloc]initWithCustomView:q],[[UIBarButtonItem alloc]initWithCustomView:s],[[UIBarButtonItem alloc]initWithCustomView:g]]; }
%new - (UIMenu *)ag_gestureMenu { ActionGestureHelper *h=ActionGestureHelper.sharedHelper; NSMutableArray *items=[NSMutableArray array]; for(NSString *g in @[AGGestureSingle,AGGestureDouble,AGGestureLong]) { UIAction *a=[UIAction actionWithTitle:[h titleForGesture:g] image:[UIImage systemImageNamed:[h symbolForGesture:g]] identifier:nil handler:^(__unused UIAction *x){ if([g isEqual:h.currentGesture])return; [h snapshotNativeConfigurationForGesture:h.currentGesture]; if(![h hasStoredConfigurationForGesture:g])[h snapshotNativeConfigurationForGesture:g]; [h saveCurrentGesture:g]; [h applyNativeConfigurationForGesture:g]; [self ag_installSelectors]; }]; a.state=[g isEqual:h.currentGesture]?UIMenuElementStateOn:UIMenuElementStateOff;[items addObject:a]; } return [UIMenu menuWithTitle:@"手势" children:items]; }
%new - (UIMenu *)ag_shortcutMenu { ActionGestureHelper *h=ActionGestureHelper.sharedHelper; if(![h canUseShortcutForGesture:h.currentGesture]){ UIAction *off=[UIAction actionWithTitle:@"关闭" image:[UIImage systemImageNamed:@"bolt.slash"] identifier:nil handler:^(__unused UIAction *x){}]; off.state=UIMenuElementStateOn; off.attributes=UIMenuElementAttributesDisabled; return [UIMenu menuWithTitle:@"快捷动作" children:@[off]]; } NSArray *shortcuts=@[AGShortcutOff,AGShortcutWeChatScan,AGShortcutWeChatPay,AGShortcutAlipayScan,AGShortcutAlipayPay]; NSMutableArray *items=[NSMutableArray array]; for(NSString *s in shortcuts){ UIAction *a=[UIAction actionWithTitle:[h titleForShortcut:s] image:[UIImage systemImageNamed:[h symbolForShortcut:s]] identifier:nil handler:^(__unused UIAction *x){[h saveShortcut:s forGesture:h.currentGesture];[self ag_installSelectors];}];a.state=[s isEqual:[h shortcutForGesture:h.currentGesture]]?UIMenuElementStateOn:UIMenuElementStateOff;[items addObject:a]; } return [UIMenu menuWithTitle:@"快捷动作" children:items]; }
- (void)viewDidLoad { %orig; ActionGestureHelper *h=ActionGestureHelper.sharedHelper; if(![h hasStoredConfigurationForGesture:h.currentGesture])[h snapshotNativeConfigurationForGesture:h.currentGesture]; [self ag_installSelectors]; }
- (void)viewWillAppear:(BOOL)animated { %orig; [self ag_installSelectors]; }
- (void)viewWillDisappear:(BOOL)animated { %orig; }
%end
%end

%ctor { @autoreleasepool { if([NSBundle.mainBundle.bundleIdentifier isEqual:@"com.apple.Preferences"]){ActionGestureHelper *h=ActionGestureHelper.sharedHelper;[h loadEditorState];if(!h.settingsBundle.loaded)[h.settingsBundle loadAndReturnError:nil];if(NSClassFromString(@"ActionButtonSettings"))%init(ActionGestureOfficialSettings);} } }
